// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmbwrbkphwjgkjupmvxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtYndyYmtwaHdqZ2tqdXBtdnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIxNjcsImV4cCI6MjA2NTQ4ODE2N30.TRrVs8baIBIvNwXRX_6O9j45J_h_-Sx3kw-XNEB30f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);